; PlatformIO project file for the ESP32 + WS2812B DIY Smart Lamp
; https://platformio.org/

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    fastled/FastLED@^3.7.0
build_flags =
    -D FASTLED_ESP32_I2S=1
